### ISSUE TITLE
import Debug

### ISSUE THREAD

**Issue by minad** [psygnisfive/SimpleFP-v2#1]
Hi Darryl,

I played around with your compilers since I am currently much interested in compiler design of strongly typed languages. Thx for your work! Two minor things:
- I wondered that you have in some REPL.hs files "import Debug" which didn't compile for me. Commenting it out works.
- Did you try megaparsec before? It seems to be a better maintained version of parsec.

Best,
Daniel

**Comment by BekaValentine** [comment]
thanks for letting me know about this! I should've removed this before pushing to github :)

as for megaparsec, no, havent tried it at all, ill have to give it a look
